### ISSUE TITLE
[Feature] Keys and locked doors

### ISSUE THREAD

**Issue by AlexandreGerault** [AlexandreGerault/mrcp-fabric#1]
# Idea

- [x] Add a key item 
- [x] Allow users to lock a door with a key
- [x] A locked door cannot be open
- [x] An unlocked door behaves like a normal wooden door
- [x] The door can only be open by the key used to lock it

**Comment by ClemtM** [comment]
La clée permet de vérouiller / dévérouiller une porte
Une porte verrouillée ne peut pas s'ouvrir
Une fois déverrouillée la porte se comporte comme une porte en bois classique
Une clée est spécifique à une porte

Ajouts supplémentaires : 
Le même système mais pour un coffre
Une option pour que le clique droit ne déverrouille pas mais simplement ouvre la porte mais que la porte se ferme toute seule après une temporisation ou un signal redstone

**Comment by AlexandreGerault** [comment]
Few behaviors have been noticed as potentially undesirable:
- A locked door can be opened by a redstone signal
- A locked door can be broken and then placed again, with all its state wiped out

**Comment by AlexandreGerault** [comment]
The game crash when using key on a stair:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 5/19/22, 9:11 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property class_2754{name=half, clazz=class net.minecraft.class_2756, values=[upper, lower]} as it does not exist in Block{minecraft:cobblestone_stairs}
    at net.minecraft.class_2688.method_11654(class_2688.java:98)
    at alexandregerault.mcrp.lock.KeyItem.method_7884(KeyItem.java:31)
    at net.minecraft.class_1799.method_7981(class_1799.java:250)
    at net.minecraft.class_636.method_2896(class_636.java:339)
    at net.minecraft.class_310.method_1583(class_310.java:1659)
    at net.minecraft.class_310.method_1508(class_310.java:1912)
    at net.minecraft.class_310.method_1574(class_310.java:1739)
    at net.minecraft.class_310.method_1523(class_310.java:1091)
    at net.minecraft.class_310.method_1514(class_310.java:737)
    at net.minecraft.client.main.Main.main(Main.java:236)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:577)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
```

**Comment by AlexandreGerault** [comment]
Fixed in #2
